/*
 * Copyright 2026 The A2UI Vue Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {Component, VNode} from 'vue';
import type {
  ComponentApi,
  ComponentContext,
  ComponentNode,
  InferredComponentApiSchemaType,
  ResolveA2uiProps,
} from '@a2ui/web_core/v0_9';

/**
 * Renders a resolved child node, or falls back for an unresolved id.
 *
 * Mirrors `NodeBuildChild` in the React renderer so that catalog component
 * sources stay readable across framework adapters.
 */
export type VueBuildChild = (
  child: ComponentNode<VueComponentImplementation> | string,
  basePath?: string,
) => VNode | VNode[] | string;

/** What a catalog component's render function receives. */
export interface VueA2uiComponentProps<T> {
  /** The bound, resolved props for this component instance. */
  props: T;
  /** Renders a child node by id/token. */
  buildChild: VueBuildChild;
  /** The A2UI context (surface + data path) this instance lives in. */
  context: ComponentContext;
}

/** A catalog component's render function (a Vue setup-style renderer). */
export type VueA2uiRenderFn<T> = (args: VueA2uiComponentProps<T>) => VNode | string | null;

/**
 * A component implementation in the Vue adapter.
 *
 * `render` receives a `context` and a `buildChild` and binds its own props
 * through the adapter's binder helper. `view` (generated by
 * {@link createComponentImplementation}) is the fast path: it reads props the
 * node layer already resolved, avoiding a second resolution pass.
 */
export interface VueComponentImplementation extends ComponentApi {
  /** The framework-specific rendering wrapper (a Vue component). */
  render: Component;
  /** Renders this component from a resolved `ComponentNode`. */
  view?: Component;
}

/** Props handed to a generated `view` component. */
export interface VueNodeViewProps {
  node: ComponentNode<VueComponentImplementation>;
  buildChild: VueBuildChild;
}

/** Convenience alias for the resolved props of an API schema. */
export type PropsOf<Api extends ComponentApi> = ResolveA2uiProps<
  InferredComponentApiSchemaType<Api>
>;
